"""empty message

Revision ID: 0ea13f8640d9
Revises: d844b82ad5a3
Create Date: 2021-08-17 12:04:11.737533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea13f8640d9'
down_revision = 'd844b82ad5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pic_ratings', sa.Column('img_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_pic_ratings_img_name'), 'pic_ratings', ['img_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pic_ratings_img_name'), table_name='pic_ratings')
    op.drop_column('pic_ratings', 'img_name')
    # ### end Alembic commands ###
