"""empty message

Revision ID: 2ee198e2282b
Revises: 0ea13f8640d9
Create Date: 2021-08-20 11:57:32.068435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee198e2282b'
down_revision = '0ea13f8640d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pic_ratings', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pic_ratings', 'notes')
    # ### end Alembic commands ###
