"""empty message

Revision ID: 51c1a5bae1a6
Revises: c95caf7133a0
Create Date: 2021-08-26 14:06:16.508184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c1a5bae1a6'
down_revision = 'c95caf7133a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_ratings', sa.Column('distort_notes', sa.String(), nullable=True))
    op.add_column('scan_ratings', sa.Column('SBF_corr_notes', sa.String(), nullable=True))
    op.add_column('scan_ratings', sa.Column('full_brain_notes', sa.String(), nullable=True))
    op.add_column('scan_ratings', sa.Column('CIFTI_notes', sa.String(), nullable=True))
    op.add_column('scan_ratings', sa.Column('dropout_notes', sa.String(), nullable=True))
    op.create_index(op.f('ix_scan_ratings_CIFTI_notes'), 'scan_ratings', ['CIFTI_notes'], unique=False)
    op.create_index(op.f('ix_scan_ratings_SBF_corr_notes'), 'scan_ratings', ['SBF_corr_notes'], unique=False)
    op.create_index(op.f('ix_scan_ratings_distort_notes'), 'scan_ratings', ['distort_notes'], unique=False)
    op.create_index(op.f('ix_scan_ratings_dropout_notes'), 'scan_ratings', ['dropout_notes'], unique=False)
    op.create_index(op.f('ix_scan_ratings_full_brain_notes'), 'scan_ratings', ['full_brain_notes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_ratings_full_brain_notes'), table_name='scan_ratings')
    op.drop_index(op.f('ix_scan_ratings_dropout_notes'), table_name='scan_ratings')
    op.drop_index(op.f('ix_scan_ratings_distort_notes'), table_name='scan_ratings')
    op.drop_index(op.f('ix_scan_ratings_SBF_corr_notes'), table_name='scan_ratings')
    op.drop_index(op.f('ix_scan_ratings_CIFTI_notes'), table_name='scan_ratings')
    op.drop_column('scan_ratings', 'dropout_notes')
    op.drop_column('scan_ratings', 'CIFTI_notes')
    op.drop_column('scan_ratings', 'full_brain_notes')
    op.drop_column('scan_ratings', 'SBF_corr_notes')
    op.drop_column('scan_ratings', 'distort_notes')
    # ### end Alembic commands ###
