"""empty message

Revision ID: 73c016de92a3
Revises: 2ee198e2282b
Create Date: 2021-08-23 16:40:05.829399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c016de92a3'
down_revision = '2ee198e2282b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subj_name', sa.String(), nullable=True),
    sa.Column('scan_type', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_ratings_rating'), 'scan_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_scan_ratings_scan_type'), 'scan_ratings', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scan_ratings_subj_name'), 'scan_ratings', ['subj_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_ratings_subj_name'), table_name='scan_ratings')
    op.drop_index(op.f('ix_scan_ratings_scan_type'), table_name='scan_ratings')
    op.drop_index(op.f('ix_scan_ratings_rating'), table_name='scan_ratings')
    op.drop_table('scan_ratings')
    # ### end Alembic commands ###
