"""empty message

Revision ID: c95caf7133a0
Revises: 73c016de92a3
Create Date: 2021-08-23 18:57:24.906201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95caf7133a0'
down_revision = '73c016de92a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_ratings', sa.Column('scene', sa.String(), nullable=True))
    op.create_index(op.f('ix_scan_ratings_scene'), 'scan_ratings', ['scene'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_ratings_scene'), table_name='scan_ratings')
    op.drop_column('scan_ratings', 'scene')
    # ### end Alembic commands ###
