"""empty message

Revision ID: d844b82ad5a3
Revises: 
Create Date: 2021-08-14 03:33:23.758428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd844b82ad5a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usernames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('pass_hash', sa.String(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usernames_username'), 'usernames', ['username'], unique=True)
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_timestamp'), 'broadcasts', ['timestamp'], unique=False)
    op.create_table('pic_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usernames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pic_ratings_rating'), 'pic_ratings', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pic_ratings_rating'), table_name='pic_ratings')
    op.drop_table('pic_ratings')
    op.drop_index(op.f('ix_broadcasts_timestamp'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index(op.f('ix_usernames_username'), table_name='usernames')
    op.drop_table('usernames')
    # ### end Alembic commands ###
